### ISSUE TITLE
Fix rhea in allbase 

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/allbase#11]
This a good issue to get @TimothyStiles up-to-date with how allbase is deployed and such. Basically, I fixed the code issue with #1 , but this code fix needs to be propagated to the main database. I need you to:

1. ssh into the allbase server
2. Update allbase with a new version of the rhea tables (this will require either dropping those tables in SQL or implementing incremental updates in the code itself)

I simply compiled the `cmd` directory into a script that I scp'd to the server. You may wish to do something different. Up to you. Please poke me with any questions.

**Comment by TimothyStiles** [comment]
@Koeng101 this should probably update on a cron job like system. Is this how all databases are being integrated at the moment?

**Comment by Koeng101** [comment]
> this should probably update on a cron job like system

Yes

> Is this how all databases are being integrated at the moment?

I ran one script and it did the thing. In the future, we want this to be on a cron job or something, redownloading the databases as needed and applying changes (in the case of rhea, it's no time at all, so dropping the tables is probably a fine solution, but uniprot we'd want incremental changes). I did not set up a cron job system just so we could get this up and running ASAP.

**Comment by TimothyStiles** [comment]
Aye. @Koeng101. Is this update necessary or more of a training exercise for me? 😉

**Comment by Koeng101** [comment]
Both. We can't do mapping to chebi's without it, but it'd also be nice for you to interact with the data a little bit :)

It honestly wouldn't take me very long to do it, but thought it would perhaps be a good exercise. If you're busy, however, I can go do it.

**Comment by TimothyStiles** [comment]
@Koeng101 if you can update it that'd be great. I'm finishing my draft for the poly refactor for everyone to review and then seeing if I can get the roadmap draft done by tonight. Will be able to look at allbase tomorrow.
